### ISSUE TITLE
Request to be able to run the game and try to improve the code.

### ISSUE THREAD

**Issue by xDidier901** [jay-yeo/battleship#7]
Hi, i'm a just graduated software engineer and I would like to contribute to some open source project. This one looks interesting. Java is my favorite language and I hope I can be able to help you guys.

**Comment by jay-yeo** [comment]
Thank you for your interest! We are all students as well, and unfortunately this is an ongoing project as part of our studies. However, once we push v1.0, we would certainly enjoy collaborating further with programmers like yourself!
